config/routes.rb
Cauzly::Application.routes.draw do
  
  
  
  

  

 

  get "invites/index"
    get "invites/invite_email"
      post "invites/invite_email"

  devise_for :users, :controllers => {:registrations => "registrations" } do
    match  'not_me' => 'registrations#not_me', :as => :not_me 
    match 'users/sign_up/fbinvite'=>'registrations#fbinvite',:as=> :fb_invite
  end
  get 'follow/user/:id' => 'follow#follow', :as => 'follow_user'
  get 'dashboard/(:id)/follower' => 'follow#follower', :as => 'user_follower'
  get 'unfollow/user/:id' => 'follow#unfollow', :as => 'unfollow_user'
  get 'block/follower/:id' => 'follow#block', :as => 'block_follower'
  get 'dashboard/(:id)/following' => 'follow#following', :as => 'user_following'
   
  
  match  'dashboard' => 'dashboard#index', :as => :dashboard 
  match 'dashboard/profile' => 'dashboard#my_profile',:as => :dashboard_profile
  match  'dashboard/update/address' => 'dashboard#update_address', :as => :user_address_update 
  match  'dashboard/update/payment_receiving_info' => 'dashboard#payment_receiving_info', :as => :payment_receiving_info 
  match 'dashboard/update/profile'=> 'dashboard#update_profile', :as => :update_profile
  match 'dashboard/images'   => 'dashboard#images',:as => :userimages
  match 'dashboard/videos'   => 'dashboard#videos',:as => :uservideos
  
  match 'dashboard/claim_username/:claim' => 'dashboard#claim_request' ,:as => :claim_request
  
  match 'home/pages/:page_id' => 'home#show_page', :as => :pages_contents
  
  resources :user_images
  resources :user_posts
 resources :settings do
   
   collection do  
    get 'changepassword'
    post 'updatepassword'
    get 'social_accounts' => "authentications#index"
   end
 end
 
 match 'get_nonprofit_from_api' => "nonprofit_search#get_nonprofit_from_api",:as => :get_nonprofit_from_api
 match 'details_donations_made' => "donation_details#details_donations_made", :as => :details_donations_made
 match 'details_donations_received' => "donation_details#details_donations_received", :as => :details_donations_received
 match 'find_non_profits' => "home#find_non_profits", :as => :find_nonprofits
  
  scope "dashboard" do
    resources :campaigns,:controller =>"user_campaigns", :as => "user_campaigns" do 
     member do
        post 'addimage'
        delete 'removeimage/:campaign_image_id' => "user_campaigns#removeimage" ,:as => :removeimage
        
        post 'addvideo'
        delete 'removevideo/:campaign_video_id' => "user_campaigns#removevideo" ,:as => :removevideo
        
        get "donations_campaigns"
        
      end
    end
  end
  
  
  resources :campaign_categories

  resources :members do 
    member do  
      match 'index/:letter' => 'members#members_index' ,:as => :members_index
      scope ':state_id' do 
        match '' => 'members#members_state' ,:as => :members_state
        match 'index/:letter' => 'members#members_state_index' ,:as => :members_state_index
      end
    end
    collection do 
      get 'filter_by_state_and_type'
      post 'filter_by_state_and_type'
    end
  end
  
  
  
 
resources :search do 
   collection do
       
      match 'causes' => "search#causes",:as => :cause
      match 'causes/:key' => "search#cause_results" ,:as => :cause_result
      
      match 'members' => 'search#members' ,:as => :members
      match 'members/:letter' => 'search#members_index' ,:as => :members_index
   end
  end
  
  
  
  resources :campaigns do
    
    collection do 
    get "filter"
    post "filter"
    match '/category/:id' => "campaigns#campaigns_by_category",:as => :by_category
    match '/filter/:sort_order'=> "campaigns#sort_order" ,:as => :filter_sort
    match ':sort_order/state/:state_id'=> "campaigns#state_sort" ,:as => :filter_state_sort
    match ':sort_order/:category_id' => "campaigns#category_sort" ,:as => :filter_category_sort
    match ':sort_order/:category_id/:state_id' => "campaigns#category_state_sort" ,:as => :filter_category_state_sort
      
    end
    get :autocomplete_campaign_title, :on => :collection
    
    collection do
      get "listed_featured_campaign"
    end
    
   end
  
  
  
  
  match '/auth/:provider/callback' => 'authentications#create'
  match '/auth/failure' => 'authentications#failure'
  
  resources :authentications
  
  
  match 'dashboard/update/avatar' => 'dashboard#update_logo', :as => :update_logo
  match 'dashboard/update/sociallinks' => 'dashboard#update_social_links', :as => :social_link_update
  match 'dashboard/update/profile_url' => 'dashboard#update_profile_name',:as => :profile_name_update
 
  match 'donors/(:filter)' => 'home#donors' ,:as => :donors
  match 'sponsors/(:filter)' => 'home#sponsors' ,:as => :sponsors
  match 'users/(:filter)' => 'home#users' ,:as => :users
  
  match 'members'    => 'home#search',:as => :member_search
   
  match 'donation_detail/:donation_id' => "profile#share_donation", :as => :donation_detail
  
  resources :donations 
  match 'makedonation/campaign/:campaign_id' => "donations#new" ,               :as => :campaign_donation
  match 'makedonation/user/:user_id'         => "donations#new" ,               :as => :user_donation 
  match 'makedonation/apiuser/:ein'          =>"donation#unregistered_donation",:as => :apiuser_donation
  
  match 'donation/apinonprofit/:uuid/:ein' => "donations#donation_apinonprofit" ,:as => :api_nonprofitdonation
  match 'makedonation/apinonprofit/:uuid/:ein' => "donations#create_donation_apinonprofit" ,:as => :api_createnonprofitdonation
  

  namespace :admin do
    match  'dashboard' => 'dashboard#index', :as => :dashboard 
    match  'individual_donation' => 'users#donations', :as => :individual_donation
    match  'campaign_donation' => 'campaigns#campaign_donations', :as => :campaign_donation
    match 'apinonprofit_donations' => 'users#api_nonprofitdonations' ,:as => :api_nonprofitdonation
    resources :campaigns do 
      member do
        get "add_to_featured"
        get "removed_from_featured"
       
      end
      
      collection do
    get "featured_campaigns"
       end
      
      
    end
    resources :states
    resources :cities
    resources :featured_users
     resources :pages
    resources :news_letters do 
      member do 
        get "send_news_letter"
      end
     
    end
   resources :reserved_usernames do
   get "approve_request"
   get "reject_request"
 
   end
   
   
   
   
    resources :users do 
    
       get 'campaigns'
      collection do 
      get 'search'
      post 'search'
      get 'filter_by_state_and_type'
      post 'filter_by_state_and_type'
    get 'bytype/:user_type_id'  => 'users#user_filter_by_type', :as => 'user_filter_by_type'
    get 'filter(/:state_id)(/:user_type_id)' => 'users#user_filter', :as => 'user_filter'
    end
       
    end
     
    
  end

  root :to => "home#index"
  

  scope '/:id' do
    match "/" =>"profile#index" , :as => :profile  
    
    match "campaigns" => "profile#campaigns" ,:as => :profile_campaigns
    match "videos" => "profile#videos" ,:as => :profile_videos
    match "images" => "profile#images" ,:as => :profile_images
    match 'follower' => 'profile#follower',:as => :profile_follower
    match 'following' => 'profile#following',:as => :profile_following
    
    match'campaigns/:campaign_id' => "profile#campaign_detail" ,:as => :user_campaign_detail
  end

end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < ApplicationController
  layout "admin"
  before_filter :require_admin
  def index
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  layout "userprofile"
  before_filter :require_login
  #before_filter :load_user
  
  #before_filter :update_profile , :only =>[:nonprofit_profile,:sponsor_profile,:donor_profile]
 
  def index
     if current_user.profile.blank?
      redirect_to update_profile_url ,:alert => "Please  fill in required fields." 
    end
    #all values loaded from load_user filter
    @user   =   current_user
    @associated_providers = current_user.authentications.map{|authentication| authentication.provider}
    @not_yet_associated_providers =  SUPPORTED_PROVIDER - @associated_providers
  
  # this is for feed
  @following_ids = @user.all_following.map{|user| user.id}
  
  @following_ids << current_user.id
  

  @feeds = ActivityFeed.where("user_id in (?)",@following_ids).order("created_at DESC").paginate(:per_page => 20,:page => params[:page])

  
  end
  
  def my_profile
    @user   =   current_user
    @associated_providers = current_user.authentications.map{|authentication| authentication.provider}
    @not_yet_associated_providers =  SUPPORTED_PROVIDER - @associated_providers
  end
  
  def update_address
      @address  = current_user.address || current_user.build_address
      if request.post?
          #@address = current_user.address
         if  @address.update_attributes(params[:address])
           redirect_to :dashboard, :notice => "Profile Information Updated successfully"
         else
         end
      end    
  end
  
 
   def update_logo
        @user_logo  = current_user.user_logo || current_user.build_user_logo
        if request.post?
            #@user_logo = current_user.user_logo
           # raise params.inspect
           if !params[:user_logo].blank?
           if @user_logo.update_attributes(params[:user_logo])
             redirect_to :dashboard, :notice => "Profile Information updated successfully"
           else
             
           end
           else
             flash[:alert] = "Please choose file to upload"
           end
        end
   end

    def images
          @user_images = current_user.user_images
         @user_image  = current_user.user_images.build
    end
 
 
  def videos
         
        if request.post?
        # raise params.inspect
         if   current_user.update_attributes(params[:user])
             redirect_to :dashboard, :notice => "Profile Information updated successfully"
        end
        else
          if current_user.user_videos.blank?
            @current_user.user_videos.build
          else
            @user_videos = current_user.user_videos
          end
        end
  end
 
 
    def update_social_links
        @social_link  = current_user.social_link || current_user.build_social_link
        if request.post?
            #@social_link = current_user.social_link
          if  @social_link.update_attributes(params[:social_link])
             redirect_to :dashboard, :notice => "Profile Information updated successfully"
          else
          end
        end
    end
   
   def update_profile_name
        @user  = current_user
        if request.post?
          @user.profile_name = params[:user][:profile_name]
          if !@user.profile_name_clamable?
          if  @user.save
             redirect_to :dashboard, :notice => "Profile Information updated successfully"
          end
          else
          
          end
        end
    end
 
 
 def claim_request
  @user = current_user
  if !params[:claim].blank?
            @reserved_name=ReservedUsername.find_by_username(params[:claim])
                   if @reserved_name
                   if @reserved_name.update_attributes(:user_id =>current_user.id )
                       redirect_to update_profile_url, :notice => "Request successfully received for processing"
    
                        else
                              redirect_to update_profile_url, :notice => "Your Request is not Processed"
                            end
                    else
                       redirect_to dashboard_url, :alert => "Some error occured."
    
                    end
   else
     redirect_to  update_profile_url
   end
   
 end
 
 
 
 
 
     def update_profile
        @profile  = current_user.profile || current_user.build_profile
        if request.post?
             @profile = current_user.profile
             if @profile.update_attributes(params[:profile])
               redirect_to :dashboard, :notice => "Profile Information Updated successfully"
             end
             
        end
     end
 
 def payment_receiving_info
        @payment_receiving_info  = current_user.payment_receiving_info || current_user.build_payment_receiving_info
        if request.post?
             @payment_receiving_info = current_user.payment_receiving_info
             if @payment_receiving_info.update_attributes(params[:payment_receiving_info])
               redirect_to :dashboard, :notice => "Payment receiving information Updated successfully"
             end
             
        end
     end
 
   #filter method to redirect current user to corresponding update method
#   def update_profile
#      if current_user.is_nonprofit?
#        redirect_to :nonprofit_profile_update
#      elsif current_user.is_sponsor?
#        redirect_to :sponsor_profile_update
#      else
#        redirect_to :donor_profile_update
#      end
#   end
   
  
end

app/views/dashboard/_notupdated_info.html.erb
<% if @user &&  current_user && @user == current_user %>

<% unless current_user.has_profile?  %>
	<div class="alert alert-info">
		  <a class="close" data-dismiss="alert">×</a>
    <%= link_to "Please update your profile information.",update_profile_path %>
  	</div><!-- .alert-3 -->
<% end %>
<% if current_user.has_profile? &&  !current_user.profile.description? %>
	<div class="alert alert-info">
		  <a class="close" data-dismiss="alert">×</a>
    <%= link_to "Please update your profile information.",update_profile_path %>
  	</div><!-- .alert-3 -->
<% end %>

<% if current_user.user_logo.nil?%>
	<div class="alert alert-info">
		 <a class="close" data-dismiss="alert">×</a> 
    	 <%= link_to "Please update your profile picture.",update_logo_path %>
  	</div><!-- .alert-3 -->
<% end %>

<% if current_user.profile_name.nil?%>
	<div class="alert alert-info">
		 <a class="close" data-dismiss="alert">×</a>
    	<%= link_to "Please update your Cauzly username.",profile_name_update_path %>
  	</div><!-- .alert-3 -->
<% end %>

<% if current_user.social_link.nil?%>
	<div class="alert alert-info">
		 <a class="close" data-dismiss="alert">×</a>
    	<%= link_to "Please update your social profiles. ",social_link_update_path %>
    	 	</div><!-- .alert-3 -->
  <% end %>
<% if current_user.address.nil?%>
	<div class="alert alert-info">
		 <a class="close" data-dismiss="alert">×</a>
    	 <%= link_to "Please update your address.",user_address_update_path %>
  	</div><!-- .alert-3 -->
<% end %>

<%end%>

app/views/dashboard/_user_video_fields.html.erb
  <div  class="field control-group">
  	<label class="control-label">Video url</label>
  	<div class="controls">
  		
  		<div style="display:inline;" class="btn center pull-right"><%= link_to_remove_fields "<i class='icon-remove'></i>".html_safe ,f %></div>
  		
  		<%= f.url_field :video_url,{:placeholder => "Video Url", :class=>"video_url"} %>
  	</div>
  </div>
  

app/views/dashboard/index.html.erb
	
	<%= render :partial => "user_posts/form"%>
	
	
<h3>
    <%= link_to image_tag("activity-icons.png",:style => "width:20px;height:20px")%>    
    Activity Feed
    </h3>
<hr />


<div id="feeds">
    <% unless @feeds.blank?%>
        <% @feeds.each do |feed|%>
		    <% if feed.activity_source_type=="UserPost"
		    user_post = feed.activity_source
		    %>           
                    <%= render(user_post)%>
            <%elsif feed.activity_source_type=="Donation"
                    donation = feed.activity_source
                    %>
    <div class="well box">
                    <div class="row-fluid">
                        <div class="span2">
                           <%= link_to get_avatar_small(donation.donor),profile_path(donation.donor.url_param)%>
                        </div><!-- End of span2 -->
                        
                        <div class="span8">
                                <strong><%= link_to donation.donor.profile.name,profile_path(donation.donor) if !donation.donor.profile.blank? && donation.donor.profile.name? %></strong><br>
                                 made a donation to <%if false%> <%= number_to_currency(donation.amount,:precision=>2)%><%end%> 
                                
                              <% if  donation.donatable_type =="User"%>
                              <%= link_to donation.donatable.profile.name,profile_path(donation.donatable) unless donation.donatable.profile.blank?%> 
                                
                             <%elsif donation.donatable_type == "Campaign"%>
                             <%=link_to donation.donatable.title,campaign_path(donation.donatable) if donation.donatable.title?%>
                             
                             <%elsif donation.donatable_type == "ApiNonprofit"%>
                             <%= donation.donatable.name if !donation.donatable.blank? && donation.donatable.name?%>
                                                        
                            <%end%>
                        </div><!-- End of span8 -->
                        
                        <div class="span2">
                            <small class="pull-right">
                                <em><i class="icon-time"></i><%= time_ago_in_words(donation.created_at)%> ago</em>
                            </small>
                        </div><!-- End of span2 -->
                    </div><!-- End of row-fluid -->
                    

					 </div>         

			    	<% elsif feed.activity_source_type=="Campaign"
			    	campaign= feed.activity_source
			    	%>
			    	
			    	<div class="well box">
			    	
			    	 <div class="row-fluid">
                        <div class="span2">
                                <%= link_to get_avatar_small(campaign.user),profile_path(campaign.user.url_param) %> 
                        </div><!-- End of span2 -->
                        
                        <div class="span8">
                            <strong><%= link_to campaign.user.profile.name,profile_path(campaign.user) if !campaign.user.profile.blank? && campaign.user.profile.name? %></strong><br>started new campaign 
                            <h3><%= campaign.title.humanize%></h3>
                        <p><%= campaign.description.truncate(80)%> <em>Campaign ends at  <%=  campaign.end_date.to_formatted_s(:long)  %></em></p>
                    
                        <%= link_to " Detail &nbsp; ".html_safe ,user_campaign_detail_path(campaign.user,campaign),:class=>"btn btn-mini" %>
                        
                        <%= link_to "Donate" ,user_campaign_detail_path(campaign.user,campaign),:class=>"btn btn-mini btn-primary" %>
                        </div><!-- End of span8 -->
                        
                        <div class="span2">
                            <small class="pull-right">
                                <em><i class="icon-time"></i> <%= time_ago_in_words(campaign.created_at)%> ago</em>
                            </small>
                        </div><!-- End of span2 -->
                    </div><!-- End of row-fluid -->
			    	 	
	              
		</div>    
					           
					<% else%>
	
					<%end%>
		    
		    
		 
	 
	<% end %>
	  <%= will_paginate @feeds ,:renderer => BootstrapLinkRenderer %>
	<% else %>
	<div class="well box" id = "no_feed">
	    No activity feeds.
	    </div>
<% end %>

 </div><!-- End of feeds -->

app/views/dashboard/payment_receiving_info.html.erb
<div class="form-horizontal">
<%= form_for(@payment_receiving_info,:url => payment_receiving_info_path,:method => :post) do |f| %>
<fieldset><legend>Paypal email</legend>
  <small>
  	Please provide your paypal merchant email address to start a campaign and collect donations.
  	<br />To create a new merchant account in paypal, Please visit  
  	<a href="http://www.paypal.com" target="_blank">http://www.paypal.com</a>
  </small>
  <br  /><br  />
  <%= render :partial => "shared/validation_msg",:locals=>{:obj=>@payment_receiving_info} %>
  
 <div class="control-group">
    <%= f.label :email ,:class=>"control-label"%>
 <div class="controls">
    <%= f.email_field :email,{:placeholder=>"Paypal merchant/premier email",:required=>true} %> *
    </div>
 </div>
 <div class="form-actions">
    	<%= f.submit "Update",:class=>"btn-primary" %>
    	
  </div>
</fieldset>
<% end %>
</div>

app/views/dashboard/update_address.html.erb
<div class="form-horizontal">


<%= form_for(@address,:url => user_address_update_path,:method => :post) do |f| %>
   <fieldset "><legend>Address</legend>
  <%= render :partial => "shared/validation_msg",:locals=>{:obj=>@address} %>
 
 <div class="control-group">
 	<div class="control-label">
    <%= f.label :address1 %>
    </div>
    <div class="controls">
    <%= f.text_field :address1,{:placeholder => "Address1",:required => true} %>
    </div>
 </div>
 <div class="control-group">
 	<div class="control-label">
    <%= f.label :address2 %>
    </div>
    <div class="controls">
    <%= f.text_field :address2,{:placeholder => "Address2"} %>
    </div>
 </div>
 
  <div class="control-group">
  	<div class="control-label">
    <%= f.label :city %>
    </div>
    <div class="controls">
    <%= f.text_field :city_name,{:placeholder => "City/Town",:required => true} %>
 </div>
 </div>
 <div class="control-group">
 	<div class="control-label">
    <%= f.label :state_id %>
    </div>
    <div class="controls">
    <%= f.collection_select :state_id,State.all,:id,:name %>
  </div>
 </div>
 <div class="control-group">
 	<div class="control-label">
    <%= f.label :zip_code %>
    </div>
    <div class="controls">
    <%= f.text_field :zip_code,{:placeholder => "Zip code",:required => true} %>
 </div>
 
 </div>
 
  <div class = "control-group">
 	
    <%= f.label :phone,:class=>"control-label" %>
    
    <div class="controls">
    	<%= f.text_field :phone,{:placeholder => "Phone",:class=>"phone"} %>
 	</div>
  </div>
 
 <div class="form-actions">
  	
  	
    	<%= f.submit "Update" %>
    </div>
 
 
</fieldset>
<% end %>
</div>

app/views/dashboard/update_logo.html.erb
<div class="form-horizontal">
<%= form_for(@user_logo,:url => update_logo_path,:method => :post,:multipart => :true) do |f| %>
  <fieldset><legend>Update profile picture</legend>
  <%= render :partial => "shared/validation_msg",:locals=>{:obj=>@user_logo} %>
  
  		<% unless @user_logo.blank? %>
  	  <% if @user_logo.attachment.exists? %>
	<div class="control-group">
  	<div class="control-label">
  	<label>Current picture</label>
  	</div>
  	<div class="controls">
  
	  	<%= image_tag @user_logo.attachment.url(:logo)%><br />
		</div>
  	</div>
    	
	  <% end %>
  <% end %>
  
  	
  <div class="control-group">
  	<div class="control-label">
   <%= f.label "Upload Image " %>
   </div>
   
   <div class="controls">
  
    <%= f.file_field :attachment%> 
	<br/> 
  	<i> Max 2MB, Image Type: JPG, JPEG, PNG, GIF<i/>
    </div>
  </div>
 
  
 
    <div class="form-actions">
    	<%= f.submit "Upload" %>
    </div>
  
  </fieldset>
<% end %>
</div>

app/views/dashboard/update_profile.html.erb
<div class="form-horizontal">

<%= form_for(@profile,:url => update_profile_path,:method => :post) do |f| %>
<fieldset><legend>Update Profile Information</legend>
  <%= render :partial => "shared/validation_msg",:locals=>{:obj=>@profile} %>
  
  <% if @profile.user.is_non_profit?%>
  <div class="control-group">
  	<%= f.label :ein, :class=>"control-label" %>
  	
  	<div class="controls">
   <%= f.text_field :ein, :disabled => true %>
    </div>
    
  	</div>
  <% end%>
  
 <div class="control-group">
    <%= f.label :name,"Name (*)" ,:class=>"control-label"%>
 <div class="controls">
    <%= f.text_field :name,{:placeholder=>"",:required=>true, :class=>"input-xlarge"} %>
    </div>
 </div>
 
 
  <div class="control-group">
    <%= f.label :website ,:class=>"control-label"%>
 	<div class="controls">
    	<%= f.url_field :website, :class=>"input-xlarge" %>
    </div>
  </div>
  
  
  
  
  
  <div class="control-group">
   <% if @profile.user.is_non_profit?%>  <%= f.label "Mission Statement",:class=>"control-label"%>
   <%else%>
   <%= f.label "About you (*)",:class=>"control-label"%>
   <%end%>
    <div class="controls">
    <%= f.text_area :description,{:placeholder=>"",:size => "66x4",:required=>true ,:style=>"width:auto;"} %>
    </div>
  </div>
  
  <div class="control-group">
    <%= f.label "Additional Info",:class=>"control-label" %>
    <div class="controls">
    <%= f.text_area :additional_information,{:placeholder=>"",:size => "66x10" ,:style=>"width:auto;",:maxlength=>"2000"} %>
    </div>
  </div>
  
  <% if current_user.is_501c_applicabale? %>
  <div class="control-group">
    <%= f.label "Are you a 501(c)(3) in good standing?" ,:class=>"control-label"%>
    <div class="controls">
    		<%= f.select :qualified_501c,[['Yes', 1],['No', 0]]%>
    		
    </div>
    </div>
  <% end %>
   <div class="form-actions">
    	<%= f.submit "Update" %>
    	
    </div>
  </fieldset>
<% end %>
</div>

app/views/dashboard/update_profile_name.html.erb
<div class="box">
<div class="form-horizontal">
	
<%= form_for(@user,:url => profile_name_update_path,:method => :post) do |f| %>
  <fieldset><legend>Update  Username</legend>
  
  <%= render :partial => "shared/validation_msg",:locals=>{:obj=>@user} %>
  <% if @user.profile_name_clamable? %>
  <div class="alert alert-error">
  	
  Cauzly has chosen to pre-reserve 4,000 usernames for selected individuals and companies.
<br />
You might be the person or company this username was reserved for.
<br />
If you would like to request this username from the administrator, 
 <%= link_to "please click here",claim_request_url(@user.profile_name) %>
 
 </div>
 
 
<%end%>

  <div class="control-group">
    <%= f.label :profile_name,:class=>"control-label" %>
    <div class="controls">
    http://cauzly.com/
    
    <%= f.text_field :profile_name ,:required=>true%>
   
    <br/>
    <i>
  	Example : http://cauzly.com/&lt;username&gt;. &nbsp;
  	<i/>
     </div>
     </div>
  	
   <div class="form-actions">
    <%= f.submit "Save" %>
  </div>
<% end %>
</div>
</div>

app/views/dashboard/update_social_links.html.erb
<div class="form-horizontal">
	
<%= form_for(@social_link,:url => social_link_update_path,:method => :post) do |f| %>
  <fieldset><legend>Social Profile Urls</legend>
  <%= render :partial => "shared/validation_msg",:locals=>{:obj=>@social_link} %>
 <div class="control-group" >
     
    <%= f.label :facebook,image_tag("FB16.png"),:class=>"control-label"%>
    <div class="controls">
    <%= f.url_field :facebook,{:placeholder=>"Your Facebook url",:class =>"input-xlarge"} %>
    </div>
    </div>
    
    <div class="control-group">
    <%= f.label :twitter ,image_tag("twitter16.png"),:class=>"control-label"%>
    <div class="controls">
    <%= f.url_field :twitter,{:placeholder=>"Your Twitter url",:class =>"input-xlarge"} %>
    </div>
    </div>
    
    <div class="control-group">
    <%= f.label :googleplus ,image_tag("g+16.png"),:class=>"control-label"%>
    <div class="controls">
    <%= f.url_field :googleplus ,{:placeholder=>"Your Googleplus url",:class =>"input-xlarge"} %>
    </div>
    </div>
  
  <div class="control-group">
     <%= f.label :linkedin,image_tag("linkedin16.png"),:class=>"control-label" %>
     <div class="controls">
    <%= f.url_field :linkedin ,{:placeholder=>"Your LinkedIn url",:class =>"input-xlarge"} %>
    </div>
  </div>
 
 <div class="control-group">
    <%= f.label :youtube,image_tag("youtube16.png"),:class=>"control-label" %>
    <div class="controls">
    <%= f.url_field :youtube ,{:placeholder=>"Your Youtube url",:class =>"input-xlarge"} %>
    </div>
  </div>
 
 <div class="control-group">
    <%= f.label :pinterest,image_tag("Pinterest.png"),:class=>"control-label" %>
    <div class="controls">
    <%= f.url_field :pinterest,{:placeholder=>"Your Pinterest url",:class =>"input-xlarge"} %>
    </div>
  </div>
  
 <div class="control-group">
    <%= f.label :foursquare,image_tag("Foursquare16.png"),:class=>"control-label" %>
    <div class="controls">
    <%= f.url_field :foursquare,{:placeholder=>"Your Foursquare url",:class =>"input-xlarge"} %>
    </div>
 </div>
 
 <div class="control-group">
 	<div class="control-label">
    <%= f.label :blog ,image_tag("blogicon16.png")%>
    </div>
    <div class="controls">
    <%= f.url_field :blog,{:placeholder=>"Your Blog url",:class =>"input-xlarge"} %>
  </div>
  </div>
  
 
  <div class="form-actions">
  	
    
    	<%= f.submit "Update" %>
    
  </div>
  </fieldset>
<% end %>
</div>