config/routes.rb
Cauzly::Application.routes.draw do
  
  
  
  

  

 

  get "invites/index"
    get "invites/invite_email"
      post "invites/invite_email"

  devise_for :users, :controllers => {:registrations => "registrations" } do
    match  'not_me' => 'registrations#not_me', :as => :not_me 
    match 'users/sign_up/fbinvite'=>'registrations#fbinvite',:as=> :fb_invite
  end
  get 'follow/user/:id' => 'follow#follow', :as => 'follow_user'
  get 'dashboard/(:id)/follower' => 'follow#follower', :as => 'user_follower'
  get 'unfollow/user/:id' => 'follow#unfollow', :as => 'unfollow_user'
  get 'block/follower/:id' => 'follow#block', :as => 'block_follower'
  get 'dashboard/(:id)/following' => 'follow#following', :as => 'user_following'
   
  
  match  'dashboard' => 'dashboard#index', :as => :dashboard 
  match 'dashboard/profile' => 'dashboard#my_profile',:as => :dashboard_profile
  match  'dashboard/update/address' => 'dashboard#update_address', :as => :user_address_update 
  match  'dashboard/update/payment_receiving_info' => 'dashboard#payment_receiving_info', :as => :payment_receiving_info 
  match 'dashboard/update/profile'=> 'dashboard#update_profile', :as => :update_profile
  match 'dashboard/images'   => 'dashboard#images',:as => :userimages
  match 'dashboard/videos'   => 'dashboard#videos',:as => :uservideos
  
  match 'dashboard/claim_username/:claim' => 'dashboard#claim_request' ,:as => :claim_request
  
  match 'home/pages/:page_id' => 'home#show_page', :as => :pages_contents
  
  resources :user_images
  resources :user_posts
 resources :settings do
   
   collection do  
    get 'changepassword'
    post 'updatepassword'
    get 'social_accounts' => "authentications#index"
   end
 end
 
 match 'get_nonprofit_from_api' => "nonprofit_search#get_nonprofit_from_api",:as => :get_nonprofit_from_api
 match 'details_donations_made' => "donation_details#details_donations_made", :as => :details_donations_made
 match 'details_donations_received' => "donation_details#details_donations_received", :as => :details_donations_received
 match 'find_non_profits' => "home#find_non_profits", :as => :find_nonprofits
  
  scope "dashboard" do
    resources :campaigns,:controller =>"user_campaigns", :as => "user_campaigns" do 
     member do
        post 'addimage'
        delete 'removeimage/:campaign_image_id' => "user_campaigns#removeimage" ,:as => :removeimage
        
        post 'addvideo'
        delete 'removevideo/:campaign_video_id' => "user_campaigns#removevideo" ,:as => :removevideo
        
        get "donations_campaigns"
        
      end
    end
  end
  
  
  resources :campaign_categories

  resources :members do 
    member do  
      match 'index/:letter' => 'members#members_index' ,:as => :members_index
      scope ':state_id' do 
        match '' => 'members#members_state' ,:as => :members_state
        match 'index/:letter' => 'members#members_state_index' ,:as => :members_state_index
      end
    end
    collection do 
      get 'filter_by_state_and_type'
      post 'filter_by_state_and_type'
    end
  end
  
  
  
 
resources :search do 
   collection do
       
      match 'causes' => "search#causes",:as => :cause
      match 'causes/:key' => "search#cause_results" ,:as => :cause_result
      
      match 'members' => 'search#members' ,:as => :members
      match 'members/:letter' => 'search#members_index' ,:as => :members_index
   end
  end
  
  
  
  resources :campaigns do
    
    collection do 
    get "filter"
    post "filter"
    match '/category/:id' => "campaigns#campaigns_by_category",:as => :by_category
    match '/filter/:sort_order'=> "campaigns#sort_order" ,:as => :filter_sort
    match ':sort_order/state/:state_id'=> "campaigns#state_sort" ,:as => :filter_state_sort
    match ':sort_order/:category_id' => "campaigns#category_sort" ,:as => :filter_category_sort
    match ':sort_order/:category_id/:state_id' => "campaigns#category_state_sort" ,:as => :filter_category_state_sort
      
    end
    get :autocomplete_campaign_title, :on => :collection
    
    collection do
      get "listed_featured_campaign"
    end
    
   end
  
  
  
  
  match '/auth/:provider/callback' => 'authentications#create'
  match '/auth/failure' => 'authentications#failure'
  
  resources :authentications
  
  
  match 'dashboard/update/avatar' => 'dashboard#update_logo', :as => :update_logo
  match 'dashboard/update/sociallinks' => 'dashboard#update_social_links', :as => :social_link_update
  match 'dashboard/update/profile_url' => 'dashboard#update_profile_name',:as => :profile_name_update
 
  match 'donors/(:filter)' => 'home#donors' ,:as => :donors
  match 'sponsors/(:filter)' => 'home#sponsors' ,:as => :sponsors
  match 'users/(:filter)' => 'home#users' ,:as => :users
  
  match 'members'    => 'home#search',:as => :member_search
   
  match 'donation_detail/:donation_id' => "profile#share_donation", :as => :donation_detail
  
  resources :donations 
  match 'makedonation/campaign/:campaign_id' => "donations#new" ,               :as => :campaign_donation
  match 'makedonation/user/:user_id'         => "donations#new" ,               :as => :user_donation 
  match 'makedonation/apiuser/:ein'          =>"donation#unregistered_donation",:as => :apiuser_donation
  
  match 'donation/apinonprofit/:uuid/:ein' => "donations#donation_apinonprofit" ,:as => :api_nonprofitdonation
  match 'makedonation/apinonprofit/:uuid/:ein' => "donations#create_donation_apinonprofit" ,:as => :api_createnonprofitdonation
  

  namespace :admin do
    match  'dashboard' => 'dashboard#index', :as => :dashboard 
    match  'individual_donation' => 'users#donations', :as => :individual_donation
    match  'campaign_donation' => 'campaigns#campaign_donations', :as => :campaign_donation
    match 'apinonprofit_donations' => 'users#api_nonprofitdonations' ,:as => :api_nonprofitdonation
    resources :campaigns do 
      member do
        get "add_to_featured"
        get "removed_from_featured"
       
      end
      
      collection do
    get "featured_campaigns"
       end
      
      
    end
    resources :states
    resources :cities
    resources :featured_users
     resources :pages
    resources :news_letters do 
      member do 
        get "send_news_letter"
      end
     
    end
   resources :reserved_usernames do
   get "approve_request"
   get "reject_request"
 
   end
   
   
   
   
    resources :users do 
    
       get 'campaigns'
      collection do 
      get 'search'
      post 'search'
      get 'filter_by_state_and_type'
      post 'filter_by_state_and_type'
    get 'bytype/:user_type_id'  => 'users#user_filter_by_type', :as => 'user_filter_by_type'
    get 'filter(/:state_id)(/:user_type_id)' => 'users#user_filter', :as => 'user_filter'
    end
       
    end
     
    
  end

  root :to => "home#index"
  

  scope '/:id' do
    match "/" =>"profile#index" , :as => :profile  
    
    match "campaigns" => "profile#campaigns" ,:as => :profile_campaigns
    match "videos" => "profile#videos" ,:as => :profile_videos
    match "images" => "profile#images" ,:as => :profile_images
    match 'follower' => 'profile#follower',:as => :profile_follower
    match 'following' => 'profile#following',:as => :profile_following
    
    match'campaigns/:campaign_id' => "profile#campaign_detail" ,:as => :user_campaign_detail
  end

end

app/controllers/search_controller.rb
class SearchController < ApplicationController
   #autocomplete :brand, :name
  # GET /causes
  # GET /causes.json
  
  def causes
    @key =""
   if params[:cause_keyword]
    @key =  params[:cause_keyword]
     #@causes = Cause.where("title like ? and end_date < ?" , params[:cause_search][:keyword]+"%",Time.now).paginate(:per_page => 1,:page => params[:page])
     @causes = Campaign.where("title like ?" , "%"+@key+"%").paginate(:per_page => 5,:page => params[:page])
   else
     @causes = Campaign.where("end_date <> ?",Time.now).paginate(:per_page => 5,:page => params[:page])
   end
   
  end
 
 
  def members
    @states = State.all
    @user_types = UserType.user_types
    
    
    
    if params[:members_search]
      if !params[:members_search][:state].blank? && !params[:members_search][:user_type].blank?
        state = State.find(params[:members_search][:state])
        user_type = UserType.find(params[:members_search][:user_type]) 
        @search_term  = "State : #{state.name}   Type : #{user_type.name}"  
          @users =  User.joins('LEFT  JOIN addresses ON addresses.user_id = users.id').where(" addresses.state_id = ? and user_type_id = ? and user_type_id != ?  ",params[:members_search][:state],params[:members_search][:user_type],1).paginate(:per_page => 5,:page => params[:page])
      elsif params[:members_search][:state].blank?
        user_type = UserType.find(params[:members_search][:user_type]) 
        @search_term  = "Type : #{user_type.name}"  
        
          @users =  User.where(" user_type_id = ? and user_type_id != ?  ",params[:members_search][:user_type],1).paginate(:per_page => 5,:page => params[:page])
      elsif params[:members_search][:user_type].blank?
          state = State.find(params[:members_search][:state])
        @search_term  = "State : #{state.name}"  
        
          @users =  User.joins('LEFT  JOIN addresses ON addresses.user_id = users.id').where(" addresses.state_id = ?  and user_type_id != ?  ",params[:members_search][:state],1).paginate(:per_page => 5,:page => params[:page])
      else
            
      end
     
     else
    
      @users = User.where("user_type_id != 1 ").paginate(:per_page => 5,:page => params[:page])
    end
         
  end
 
 
 def members_index 
   @states = State.all
    @user_types = UserType.user_types
    @search_term  = "Alphabet   : #{params[:letter]}"
    @users =  User.joins('LEFT  JOIN profiles ON profiles.user_id = users.id').where(" profiles.name like (?)  and user_type_id != ?  ",params[:letter]+"%",1).paginate(:per_page => 5,:page => params[:page])
 end 
   
 
 
  
  def cause_results
    
    @causes = Cause.where("title like ?" , params[:key]+"%")
#raise @causes.inspect
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @causes }
    end
  end

  def search
    
  end  


  # GET /causes/1
  # GET /causes/1.json
  def show
    @user = User.find(params[:user_id])
    @cause = @user.causes.find(params[:id])
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @cause }
    end
  end
  
  

  # GET /causes/new
  # GET /causes/new.json
  def new
    @cause = current_user.causes.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @cause }
    end
  end

  # GET /causes/1/edit
  def edit
    @cause = current_user.causes.find(params[:id])
  end

  # POST /causes
  # POST /causes.json
  def create
    @cause = current_user.causes.new(params[:cause])

    respond_to do |format|
      if @cause.save
        format.html { redirect_to user_cause_url(@cause), notice: 'Cause was successfully created.' }
        format.json { render json: @cause, status: :created, location: @cause }
      else
        format.html { render action: "new" }
        format.json { render json: @cause.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /causes/1
  # PUT /causes/1.json
  def update
    @cause = current_user.causes.find(params[:id])

    respond_to do |format|
      if @cause.update_attributes(params[:cause])
        format.html { redirect_to user_cause_url(@cause), notice: 'Cause was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @cause.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /causes/1
  # DELETE /causes/1.json
  def destroy
    @cause = current_user.causes.find(params[:id])
    @cause.destroy

    respond_to do |format|
      format.html { redirect_to user_causes_url }
      format.json { head :no_content }
    end
  end
  
   def addimage
     @cause = current_user.causes.find(params[:id])
     @cause_image = @cause.cause_images.build(params[:cause_image])
     if @cause_image.save
       redirect_to user_cause_url(@cause)
     end
  end
  
  def removeimage
    @cause = current_user.causes.find(params[:id])
     @cause_image = @cause.cause_images.find(params[:cause_image_id])
     if @cause_image.destroy
       
       redirect_to user_cause_url(@cause)
     else
       redirect_to user_cause_url(@cause) ,:alert => "Some error occured" 
     end
  end 

 def addvideo
     @cause = current_user.causes.find(params[:id])
     @cause_video = @cause.cause_videos.build(params[:cause_video])
     if @cause_video.save
       redirect_to user_cause_url(@cause)
     end
  end

  def removevideo
    @cause = current_user.causes.find(params[:id])
     @cause_video = @cause.cause_videos.find(params[:cause_video_id])
     if @cause_video.destroy
       
       redirect_to user_cause_url(@cause)
     else
       redirect_to user_cause_url(@cause) ,:alert => "Some error occured" 
     end
  end
  
end

app/views/search/_member_filter.html.erb
<ul class="breadcrumb">
<% "A".upto("Z") do |l| -%> 
	<li><%= link_to_unless_current l, members_index_search_index_path(:letter => l) %><span class="divider">|</span></li>
 
<% end %>
</ul>

app/views/search/cause_results.html.erb
	<h3>Causes</h3>
	
	<% @causes.each do |cause| %>
		 <div class="feedBox">	<div style="float: left;width:110px;">
		<% if cause.default_image && cause.default_image.attachment.exists? %>
			<%= image_tag(cause.default_image.attachment(:thumb))%>
		<% end %>
		</div>
		<div style="margin-left: 120px;">
		<h3><%= cause.title%></h3>
		 	 <p><%= cause.description.truncate(400)%></p>
			 <p>Cause ends at <em> <%=  cause.end_date.to_formatted_s(:long)  %></em> &nbsp;
			 </p>
			 	<%= link_to "View Detail" ,cause_path(cause.user,cause),:class=>"read-more" %>
		</div>

		 </div>

	<% end %>

app/views/search/causes.html.erb
<div class="row-fluid">
	<div class="span3">
<div class="" style="border-right: solid #888888 1px;">
 well
</div>
	</div>
<div class="span9">	
	<div class="well">
<%= link_to "View All " ,cause_search_index_path%>
		<div class="myform" style="text-align: right;">
			
				<%= form_for(:cause_search ,:url => :cause_search_index,:method=>:get) do |f|%>
				
				
				<lable>Find a cause</label> &nbsp;<%=  autocomplete_field_tag 'cause_keyword', @key, autocomplete_campaign_title_campaigns_path,:size=>40  %>
					<div class="button" style="display: inline; float: right;margin-left:20px;"> 
						<%= f.submit "Go"%> 
			</div>
				<% end %>			 
	</div>
	</div>
	<h3>Causes</h3>
	<% @causes.each do |cause| %>
		 
		<div class="row-fluid">
		<div class="span2">		
		<% if cause.default_image && cause.default_image.attachment.exists? %>
			<%= image_tag(cause.default_image.attachment(:thumb))%>
		<% else %>
		<%= image_tag("no-img100.png")%>
		<%end%>
		</div>
		<div class="span8">
		
		<h3>
						 <%= link_to cause.title ,campaign_path(cause.user,cause) %>
			    </h3>
		 	 <p><%= cause.description.truncate(400)%></p>
			 <p>Cause ends at <em> <%=  cause.end_date.to_formatted_s(:long)  %></em> &nbsp;
			 </p>
			    	
			    	
</div>
<div class="span2">
	 <%= link_to "View Detail" ,campaign_path(cause.user,cause),:class=>"btn" %>
			
	</div>
		
</div>
<hr />
	<% end %>

<%= will_paginate @causes%>
</div>
</div>
</div>

app/views/search/members.html.erb
<div class="row-fluid">
	<div class="span3">
		<div class="well dateselect">
		
	<strong>Filter by state and type</strong>
	<%= form_for(:members_search ,:url => :members_search_index,:method=>:get) do |f|%>
		<%= f.collection_select :state,@states ,:id,:name,:include_blank=>"Select State"%>
		<%= f.collection_select :user_type,@user_types ,:id,:name,:include_blank=>"Select Member Type"%>
				
			<div class="button" style="display: inline-block; ">
		<%= f.submit "Go", :style=>"float: none;"%>
		</div>
		
	<% end %>
	

			</div>
	</div>
<div class="span9">
	 <ul class="breadcrumb">
		    <li>
		   		<%= link_to "<i class='icon-home'></i>Home".html_safe,root_path%>
		     	<span class="divider">/</span>
		    </li>
		    
		    <li class="active">Members</li>
		   
		   
    	</ul>
	<%= render :partial =>"member_filter"%>
	
	
	
	<h3>Members  <span style="color: #3B95D5;margin-left: 100px;"><%= @search_term unless @search_term.blank?%></span></h3>
	
	
	<% unless @users.empty?%>
		<% @users.each do |user| %>
			<div class="well">
			<div class="row-fluid">
					
			    <div class="span3 ">
				    <% unless user.user_logo.nil? %>
						<%= link_to(image_tag(user.user_logo.attachment(:thumb)),profile_path(user.url_param)) %>
					<% else %>
						<%= link_to(image_tag("no-img100.png"),profile_path(user.url_param)) %>
					<%end%>
				<br />	
					<% if !user.profile.nil? && user.profile.website? %>
			        			<a href="<%= user.profile.website%>" target = "_blank"><%= user.profile.website %></a>
							<%end%>
				</div>
			    <div class="span7">
			    		<% unless user.profile.nil? %>
		                  	<h3><%= link_to user.profile.name ,profile_path(user.url_param),:class=>"" %></h3>
		                    <p><%= user.profile.description.truncate(180)%></p>
			       		
		    		   	<% else %>
						   <h3>&nbsp;</h3>
					      	<p>&nbsp;</p>
						<% end %>
						                
				</div><!-- .divCharity -->
				<div class="span2">
					 <div class="alert alert-info"><em><%= user.user_type.name %></em></div>
					
					<%= link_to "View Detail",profile_path(user.url_param),:class=>"btn btn-primary" %></div>
		   
		    </div>
		    </div>
		    
		 <% end %>
		<%= will_paginate @users%>
	<% else %>
	Sorry no records found!
	<% end %>
	
</div>
</div>







	<div class="leftPanel">
	
		
	
	<div class="box">
	    <p><label>Filter by</label></p>
	<%= form_for(:filter_by_state_and_type_members ,:url => :filter_by_state_and_type_members,:method=>:post) do |f|%>
		<%= f.text_field :q,:placeholder=>"search keyword",:class=>"input"%>
		
		<% unless @state.blank?%>
		<%=f.collection_select(:state, @states, :id, :name,
          {:prompt => "All States",  :selected => @state.id})%>
			<%else%>
			<%=f.collection_select(:state, @states, :id, :name,
          {:prompt => "All States",  :selected => ""})%>
          <%end%>	
			<% unless @user_type.blank?%>
			<%= select_tag 'filter_by_state_and_type_members[user_type]', 
options_from_collection_for_select(@user_types,'id','name',@user_type.id) 
%>	<% else %>
<%=f.collection_select(:state, @user_types, :id, :name)%>
<% end %>
			
		<%= f.submit "Go" ,:class =>"viewProfile"%>
		
		
	<% end %>
</div>
	

			
	</div>
<div class="rightPanel">
	 <ul class="breadcrumb">
		    <li>
		   		<%= link_to "<i class='icon-home'></i>Home".html_safe,root_path%>
		     	<span class="divider">/</span>
		    </li>
		    <li class="active">Members<span class="divider">/</span></li>
			
		    <li class="active"><%= @user_type.name.humanize%><span class="divider">/</span></li>
		    <li><%= @search_term.html_safe unless @search_term.blank?%></li>		   
		   
    	</ul>
    	
	<%= render :partial =>"member_filter"%>
	
	
	
	
	
	<% unless @users.empty?%>
		<% @users.each do |user| %>
			<div class="well box">
			<div class="row-fluid">
					
			    <div class="span2">
						
								<div class="">
						<%= link_to get_avatar_small(user),profile_path(user.url_param) %>
										</div>
					
				
								
				</div>
				
			    <div class="span8">
			    		<% unless user.profile.nil? %>
		                  	<h3><%= link_to user.profile.name ,profile_path(user.url_param),:class=>"" %></h3>
		                    <p><%= user.profile.description.truncate(100) if user.profile.description?%></p>
			       		
		    		   	<% else %>
						   <h3>&nbsp;</h3>
					      	<p>&nbsp;</p>
						<% end %>
						<% if !user.profile.nil? && user.profile.website? %>
			        			<a href="<%= user.profile.website%>" target = "_blank"><%= user.profile.website %></a>
							<%end%>
					                
				</div><!-- .divCharity -->
				<div class="span2"> 
					<% if current_user%>
					<% @user = user%>
					<%if current_user.id!=@user.id%>
						<div class="followlinks_<%= @user.id%>">
							
							<%= render :partial => "follow/followunfollow_links"%>
							
						 </div>
						<%end%> 
						<% end %>
	
			
					
					<br /> 
					<%= link_to "Detail",profile_path(user.url_param),:class=>"btn btn-primary" %></div>
		   		

		    </div>
		    </div>
		    
		 <% end %>
		<%= will_paginate @users ,:renderer => BootstrapLinkRenderer %>
	<% else %>
	Sorry no records found!
	<% end %>
	
	<hr />
	<strong>Didn't find nonprofit you looking for to donate? Search here</strong>
	<hr />
	<div id="fgGraphWidgetContainer"></div>

    <script>

    var FG_GRAPHWIDGET_PARAMS = {

    results : {

    selectaction : function(uuid, charity_name, ein) {

    //alert('SELECTED ' + charity_name + ' ' + uuid + ' ein (' + ein + ')');
     window.location.href = '/donation/apinonprofit/'+uuid+"/"+ein;

    }

    }

    };

    </script>

    <script src="http://assets.firstgiving.com/graphwidget/static/js/fg_graph_widget.min.js"></script>
	<style>
		#fgGraphWidgetContainer{width:auto !important;}
		#fgGraphWidgetContainer #fgResults{width:auto !important;}
	</style>
	
</div>




















    

app/views/search/members_index.html.erb
<div class="row-fluid">
	<div class="span3">
		
		sdafs
	</div>
<div class="span9">
	<h3>Member Search</h3>
	<%= render :partial =>"member_filter"%>
	
	<h3>Members  <span style="color: #3B95D5;margin-left: 100px;"><%= @search_term unless @search_term.blank?%></span></h3>
	
	
	<% unless @users.empty?%>
		<% @users.each do |user| %>
			<article>
				
			    <div class="avtar">
				    <% unless user.user_logo.nil? %>
						<%= link_to(image_tag(user.user_logo.attachment(:thumb)),profile_path(user.url_param)) %>
					<% else %>
						<%= link_to(image_tag("no-img100.png"),profile_path(user.url_param)) %>
					<%end%>
				<br />	
					<% if !user.profile.nil? && user.profile.website? %>
			        			<a href="<%= user.profile.website%>" target = "_blank"><%= user.profile.website %></a>
							<%end%>
				</div>
			    <div class="divCharity">
			    	<div style="text-align: right"><em><%= user.user_type.name %></em></div>
						<% unless user.profile.nil? %>
		                  	<h3><%= link_to user.profile.name ,profile_path(user.url_param),:class=>"" %></h3>
		                    <p><%= user.profile.description.truncate(350)%></p>
			        		
		    		   	<% else %>
						   <h3>&nbsp;</h3>
					      	<p>&nbsp;</p>
						<% end %>
						<p align="right"><%= link_to "View Detail",profile_path(user.url_param),:class=>"read-more" %></p>                
				</div><!-- .divCharity -->
		    </article>
		 <% end %>
		<%= will_paginate @users%>
	<% else %>
	Sorry no records found!
	<% end %>
	</div>
</div>

app/views/search/show.html.erb
<%= link_to 'Back to causes', causes_path(@user) %>
	 <div class="feedBox">
		 
		 <h3><%= @cause.title%></h3>
		 <p><%= simple_format(@cause.description)%></p>
		 <p>Cause ends at <em> <%=  @cause.end_date.to_formatted_s(:long)  %></em> &nbsp;
		</p>

		  <%= link_to "Donate" ,"javascript:alert('Work on progress...')" ,:class =>"read-more"%>
<%@url = cause_url(@cause.user,@cause)
@text = @cause.title
%>
<%= render :partial => "shared/twit_this"%>
		   
	</div>
		  <% unless @cause.cause_images.blank? %>

	 <div class="feedBox">
		 <h3>Images</h3>
		  <div class="images">
		  	<% @cause.cause_images.each do |image| %>
		  	<% if image.attachment.exists?%>
			  	<div class="user_image">
			  		<%= image_tag(image.attachment(:thumb))%>
			  	</div>
		  	<%end%>
		  	<%end%> 
		  	<div class="clearboth"></div>
		  </div>

	 </div>

		  <%end%>

		  <% unless @cause.cause_videos.blank? %>

	 <div class="feedBox">
<h3>Videos</h3>
		  <div class="videos">
		  	<% @cause.cause_videos.each do |video| %>
		  	<% if video.video_url?%>
			  	<div class="user_video">
			  		<%= video.video_url_html%>
			  			<p class="video_title" >
				  			<%= video.video_title%>
				  		</p>
			  		
			  	</div>
		  	<%end%>
		  	<%end%> 
		  	<div class="clearboth"></div>
		  </div>

	 </div>

		  <%end%>