config/routes.rb
Cauzly::Application.routes.draw do
  
  
  
  

  

 

  get "invites/index"
    get "invites/invite_email"
      post "invites/invite_email"

  devise_for :users, :controllers => {:registrations => "registrations" } do
    match  'not_me' => 'registrations#not_me', :as => :not_me 
    match 'users/sign_up/fbinvite'=>'registrations#fbinvite',:as=> :fb_invite
  end
  get 'follow/user/:id' => 'follow#follow', :as => 'follow_user'
  get 'dashboard/(:id)/follower' => 'follow#follower', :as => 'user_follower'
  get 'unfollow/user/:id' => 'follow#unfollow', :as => 'unfollow_user'
  get 'block/follower/:id' => 'follow#block', :as => 'block_follower'
  get 'dashboard/(:id)/following' => 'follow#following', :as => 'user_following'
   
  
  match  'dashboard' => 'dashboard#index', :as => :dashboard 
  match 'dashboard/profile' => 'dashboard#my_profile',:as => :dashboard_profile
  match  'dashboard/update/address' => 'dashboard#update_address', :as => :user_address_update 
  match  'dashboard/update/payment_receiving_info' => 'dashboard#payment_receiving_info', :as => :payment_receiving_info 
  match 'dashboard/update/profile'=> 'dashboard#update_profile', :as => :update_profile
  match 'dashboard/images'   => 'dashboard#images',:as => :userimages
  match 'dashboard/videos'   => 'dashboard#videos',:as => :uservideos
  
  match 'dashboard/claim_username/:claim' => 'dashboard#claim_request' ,:as => :claim_request
  
  match 'home/pages/:page_id' => 'home#show_page', :as => :pages_contents
  
  resources :user_images
  resources :user_posts
 resources :settings do
   
   collection do  
    get 'changepassword'
    post 'updatepassword'
    get 'social_accounts' => "authentications#index"
   end
 end
 
 match 'get_nonprofit_from_api' => "nonprofit_search#get_nonprofit_from_api",:as => :get_nonprofit_from_api
 match 'details_donations_made' => "donation_details#details_donations_made", :as => :details_donations_made
 match 'details_donations_received' => "donation_details#details_donations_received", :as => :details_donations_received
 match 'find_non_profits' => "home#find_non_profits", :as => :find_nonprofits
  
  scope "dashboard" do
    resources :campaigns,:controller =>"user_campaigns", :as => "user_campaigns" do 
     member do
        post 'addimage'
        delete 'removeimage/:campaign_image_id' => "user_campaigns#removeimage" ,:as => :removeimage
        
        post 'addvideo'
        delete 'removevideo/:campaign_video_id' => "user_campaigns#removevideo" ,:as => :removevideo
        
        get "donations_campaigns"
        
      end
    end
  end
  
  
  resources :campaign_categories

  resources :members do 
    member do  
      match 'index/:letter' => 'members#members_index' ,:as => :members_index
      scope ':state_id' do 
        match '' => 'members#members_state' ,:as => :members_state
        match 'index/:letter' => 'members#members_state_index' ,:as => :members_state_index
      end
    end
    collection do 
      get 'filter_by_state_and_type'
      post 'filter_by_state_and_type'
    end
  end
  
  
  
 
resources :search do 
   collection do
       
      match 'causes' => "search#causes",:as => :cause
      match 'causes/:key' => "search#cause_results" ,:as => :cause_result
      
      match 'members' => 'search#members' ,:as => :members
      match 'members/:letter' => 'search#members_index' ,:as => :members_index
   end
  end
  
  
  
  resources :campaigns do
    
    collection do 
    get "filter"
    post "filter"
    match '/category/:id' => "campaigns#campaigns_by_category",:as => :by_category
    match '/filter/:sort_order'=> "campaigns#sort_order" ,:as => :filter_sort
    match ':sort_order/state/:state_id'=> "campaigns#state_sort" ,:as => :filter_state_sort
    match ':sort_order/:category_id' => "campaigns#category_sort" ,:as => :filter_category_sort
    match ':sort_order/:category_id/:state_id' => "campaigns#category_state_sort" ,:as => :filter_category_state_sort
      
    end
    get :autocomplete_campaign_title, :on => :collection
    
    collection do
      get "listed_featured_campaign"
    end
    
   end
  
  
  
  
  match '/auth/:provider/callback' => 'authentications#create'
  match '/auth/failure' => 'authentications#failure'
  
  resources :authentications
  
  
  match 'dashboard/update/avatar' => 'dashboard#update_logo', :as => :update_logo
  match 'dashboard/update/sociallinks' => 'dashboard#update_social_links', :as => :social_link_update
  match 'dashboard/update/profile_url' => 'dashboard#update_profile_name',:as => :profile_name_update
 
  match 'donors/(:filter)' => 'home#donors' ,:as => :donors
  match 'sponsors/(:filter)' => 'home#sponsors' ,:as => :sponsors
  match 'users/(:filter)' => 'home#users' ,:as => :users
  
  match 'members'    => 'home#search',:as => :member_search
   
  match 'donation_detail/:donation_id' => "profile#share_donation", :as => :donation_detail
  
  resources :donations 
  match 'makedonation/campaign/:campaign_id' => "donations#new" ,               :as => :campaign_donation
  match 'makedonation/user/:user_id'         => "donations#new" ,               :as => :user_donation 
  match 'makedonation/apiuser/:ein'          =>"donation#unregistered_donation",:as => :apiuser_donation
  
  match 'donation/apinonprofit/:uuid/:ein' => "donations#donation_apinonprofit" ,:as => :api_nonprofitdonation
  match 'makedonation/apinonprofit/:uuid/:ein' => "donations#create_donation_apinonprofit" ,:as => :api_createnonprofitdonation
  

  namespace :admin do
    match  'dashboard' => 'dashboard#index', :as => :dashboard 
    match  'individual_donation' => 'users#donations', :as => :individual_donation
    match  'campaign_donation' => 'campaigns#campaign_donations', :as => :campaign_donation
    match 'apinonprofit_donations' => 'users#api_nonprofitdonations' ,:as => :api_nonprofitdonation
    resources :campaigns do 
      member do
        get "add_to_featured"
        get "removed_from_featured"
       
      end
      
      collection do
    get "featured_campaigns"
       end
      
      
    end
    resources :states
    resources :cities
    resources :featured_users
     resources :pages
    resources :news_letters do 
      member do 
        get "send_news_letter"
      end
     
    end
   resources :reserved_usernames do
   get "approve_request"
   get "reject_request"
 
   end
   
   
   
   
    resources :users do 
    
       get 'campaigns'
      collection do 
      get 'search'
      post 'search'
      get 'filter_by_state_and_type'
      post 'filter_by_state_and_type'
    get 'bytype/:user_type_id'  => 'users#user_filter_by_type', :as => 'user_filter_by_type'
    get 'filter(/:state_id)(/:user_type_id)' => 'users#user_filter', :as => 'user_filter'
    end
       
    end
     
    
  end

  root :to => "home#index"
  

  scope '/:id' do
    match "/" =>"profile#index" , :as => :profile  
    
    match "campaigns" => "profile#campaigns" ,:as => :profile_campaigns
    match "videos" => "profile#videos" ,:as => :profile_videos
    match "images" => "profile#images" ,:as => :profile_images
    match 'follower' => 'profile#follower',:as => :profile_follower
    match 'following' => 'profile#following',:as => :profile_following
    
    match'campaigns/:campaign_id' => "profile#campaign_detail" ,:as => :user_campaign_detail
  end

end

app/views/shared/_admin_nav.html.erb
<div class="DashLink">

    <ul class="breadcrumb">

		
	<li><%= link_to "Admin".html_safe ,admin_dashboard_path%><span class="divider">|</span></li>
	
	<li><%= link_to "Users".html_safe ,admin_users_path%><span class="divider">|</span></li>
    <li><%= link_to "Featured users".html_safe ,admin_featured_users_path%><span class="divider">|</span></li>
    
	<li><%= link_to "Campaigns".html_safe,admin_campaigns_path %><span class="divider">|</span></li>
    <li><%= link_to "Featured Campaigns".html_safe,featured_campaigns_admin_campaigns_path %><span class="divider">|</span></li>
    
	
	<% if false%><li><%= link_to "<i class='icon-address'></i>Cities".html_safe,admin_cities_path %></li><% end %>
	<li><%= link_to "Donations(cause)".html_safe,admin_individual_donation_path %><span class="divider">|</span></li>
	<li><%= link_to "Donations(unreg Cause)".html_safe,admin_api_nonprofitdonation_path %><span class="divider">|</span></li>
	<li><%= link_to  "Donations(Campaign)".html_safe,admin_campaign_donation_path%><span class="divider">|</span></li>
	<li><%= link_to  "Pages".html_safe,admin_pages_path%><span class="divider">|</span></li>
	<li><%= link_to "Newsletters".html_safe,admin_news_letters_path %><span class="divider">|</span></li>
    <li><%= link_to "Reserved Username".html_safe,admin_reserved_usernames_path %></li>
    
		
	</ul>
</div>

app/views/shared/_fb_share.html.erb
<fb:like href="<%= @share_url%>" width="450" height="80"/>

app/views/shared/_public_profile_nav.html.erb
<div>
    <ul class="nav nav-list">
    	<li <%if controller_name=="profile" && action_name=="index"%> class="active" <%end%>>
   			<%= link_to "<strong><i class='icon-user'></i>Profile</strong>".html_safe,profile_path(@user) %></li>
   		<% if false %>
   		
   		<li <%if controller_name=="profile" && action_name=="images"%> class="active" <%end%>>
   			<%= link_to "<strong><i class='icon-picture'></i>Images</strong>".html_safe,profile_images_path(@user) %></li>
   		<li <%if controller_name=="profile" && action_name=="videos"%> class="active" <%end%>>
   			<%= link_to "<strong><i class='icon-film'></i>Videos</strong>".html_safe,profile_videos_path(@user) %></li>
   		
   		<% end %>
   		
   		<%if @user.is_non_profit?%>
    	<li <%if(controller_name=="profile" && (action_name=="campaigns" || action_name=="campaign_detail"))%> class="active" <%end%>>
   			<%= link_to "<strong><i class='icon-th'></i>Campaigns</strong>".html_safe,profile_campaigns_path(@user) %></li>
   		
    <%end%>
    <li <%if controller_name=="profile" && action_name=="follower"%> class="active" <%end%>>
   			<%= link_to "<i class='icon-th'></i><strong>#{pluralize(@user.followers_count,'Follower')} </strong>".html_safe,profile_follower_path(@user) %></li>
    <li <%if controller_name=="profile" && action_name=="following"%> class="active" <%end%>>
   			<%= link_to "<i class='icon-th'></i><strong>#{@user.follow_count} Following</strong>".html_safe,profile_following_path(@user) %></li>
   		
    </ul>

</div>
<br />

app/views/shared/_social_share.html.erb
<div class = "social_share "> 
<div class="row-fluid">
<div class="span2">
	<div id= fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=379444142109363";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
<div class="fb-like" data-href ="<%= @share_url%>" data-send="false" data-layout ="button_count" data-width="100" data-show-faces="false"></div>
</div>
<div class="span2">
	<a href="https://twitter.com/share" class="twitter-share-button" data-url="<%= @share_url%>" data-text="<%= @share_data%>" data-via="cauzly" data-count="none" >Tweet</a>
	<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>

</div>
<div class="span2">
<!-- Place this tag where you want the share button to render. -->
<div class="g-plus" data-action="share" data-annotation="none" data-href="<%= @share_url%>"></div>

<!-- Place this tag after the last share tag. -->
<script type="text/javascript">
  (function() {
    var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
    po.src = 'https://apis.google.com/js/plusone.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
  })();
</script> 
</div>
<div class="span2">
<script src="//platform.linkedin.com/in.js" type="text/javascript"></script>
<script type="IN/Share" data-url="<%= @share_url%>"></script>
</div>
<div class="span2">
<a href="http://pinterest.com/pin/create/button/?url=<%= @share_url%>&media=https%3A%2F%2Fcauzly.com%2Fassets%2Flogo.png&description=<%= @share_data%>" class="pin-it-button" count-layout="none"><img border="0" src="//assets.pinterest.com/images/PinExt.png" title="Pin It" /></a>
<script type="text/javascript" src="//assets.pinterest.com/js/pinit.js"></script>
</div>


</div>
</div>

app/views/shared/_twit_this.html.erb
<a href="http://twitter.com/share" class="twitter-share-button"  data-text = "<%=@text%>" data-url="<%= @url %>" data-counturl="<%= @url %>" data-via ="cauzly"  data-count="horiznotal">Tweet</a>
<script type="text/javascript" src="http://platform.twitter.com/widgets.js"></script> 

app/views/shared/_user_profile_nav.html.erb
<div>
    <ul class="nav nav-list">
   		<li <%if controller_name=="dashboard" && action_name=="index"%> class="active" <%end%>>
   			<%= link_to "<i class='icon-list-alt'></i>Dashboard".html_safe ,dashboard_path%></li>
    	<% if false %>
    	<li <%if controller_name=="dashboard" && action_name=="profile"%> class="active" <%end%>>
   			<%= link_to "<i class='icon-user'></i>Profile".html_safe ,dashboard_profile_path%></li>
    	<% end %>
    	<% if controller_name == "authentications" || controller_name == "settings" %>
 			<li class="nav-header"><i class='icon-cog'></i>Settings</li> 
 			<li <%if controller_name=="settings" && action_name=="changepassword"%> class="active" <%end%>>
 				<%= link_to "<i class='icon-edit'></i>Change Password".html_safe,changepassword_settings_path%></li>
 			<li <%if controller_name=="authentications" && action_name=="index"%> class="active" <%end%>>
 				<%= link_to "<i class='icon-edit'></i>Facebook/Twitter Account".html_safe,social_accounts_settings_path%></li>
 	 	<% else %>
    	
    	
    	<li <%if controller_name=="dashboard" && action_name=="update_profile"%> class="active" <%end%>>
    		<%= link_to "<i class='icon-edit'></i>General Info".html_safe,update_profile_path %></li>
    	<li <%if controller_name=="dashboard" && action_name=="update_logo"%> class="active" <%end%>>
    		<%= link_to "<i class='icon-picture'></i>Profile Picture".html_safe,update_logo_path %></li>
    	<li <%if controller_name=="dashboard" && action_name=="update_profile_name"%> class="active" <%end%>>
    		<%= link_to "<i class='icon-edit'></i>Username".html_safe ,profile_name_update_path%></li>
   		<li <%if controller_name=="dashboard" && action_name=="update_social_links"%> class="active" <%end%>>
   			<%= link_to "<i class='icon-th'></i>Social Profiles".html_safe,social_link_update_path %></li>
   		<li <%if controller_name=="dashboard" && action_name=="update_address"%> class="active" <%end%> >
   			<%= link_to "<i class='icon-th-large'></i>Address".html_safe,user_address_update_path %></li>
   		<li <%if controller_name=="dashboard" && action_name=="images"%> class="active" <%end%>>
   			<%= link_to "<i class='icon-picture'></i>Images".html_safe,userimages_path %></li>
   		<li <%if controller_name=="dashboard" && action_name=="videos"%> class="active" <%end%>>
   			<%= link_to "<i class='icon-film'></i>Videos".html_safe,uservideos_path %></li>
   		
   		
   		
   		
   		
   		<!---<li class="divider"></li>
   		<li <%if controller_name=="dashboard" && action_name=="payment_receiving_info"%> class="active" <%end%>>
   			<%= link_to "<i class=''></i>Paypal Email".html_safe,payment_receiving_info_path %></li>
   			--->
   		
   			
   			
   			
   		<li class="divider"></li>
   		<li <%if controller_name=="user_campaigns" && action_name=="index"%> class="active" <%end%>>
   			<%= link_to "<strong><i class='icon-th'></i>Campaigns</strong>".html_safe,user_campaigns_path  if current_user.is_non_profit? %></li>
   		<%end%>
   		 <li class="divider"></li>
   		<li class=" nav-header <%if controller_name=="donation_details" && action_name=="details_donations_made"%> active <%end%>">
   			<%= link_to "My Donations",details_donations_made_path %></li>
   			
   			
   			<li class=" nav-header <%if controller_name=="donation_details" && action_name=="details_donations_received"%>active <%end%>">
   			<%= link_to "Donations Received",details_donations_received_path if current_user.is_non_profit? %></li>
   			
   		
    <li class="divider"></li>
    <li class="nav-header">
      <%= link_to "#{@user.follow_count} following", user_following_path %>
     </li>
     <li class="nav-header">
     	<%= link_to pluralize(@user.followers_count,'follower'), user_follower_path,  :class => '' %>
    
     	
     </li>
     <li class="divider"></li>
    </ul>

</div>

app/views/shared/_validation_msg.html.erb
<% if obj.errors.any? %>
    <div class="alert alert-error">
      <a class="close" data-dismiss="alert">×</a>
      <p><% if false%>
      		<strong><%= pluralize(obj.errors.count, "error") %> prohibited this action:</strong>
		<% end %>
      <ul>
      <% obj.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
      </p>
    </div>
  <% end %>