config/routes.rb
Cauzly::Application.routes.draw do
  
  
  
  

  

 

  get "invites/index"
    get "invites/invite_email"
      post "invites/invite_email"

  devise_for :users, :controllers => {:registrations => "registrations" } do
    match  'not_me' => 'registrations#not_me', :as => :not_me 
    match 'users/sign_up/fbinvite'=>'registrations#fbinvite',:as=> :fb_invite
  end
  get 'follow/user/:id' => 'follow#follow', :as => 'follow_user'
  get 'dashboard/(:id)/follower' => 'follow#follower', :as => 'user_follower'
  get 'unfollow/user/:id' => 'follow#unfollow', :as => 'unfollow_user'
  get 'block/follower/:id' => 'follow#block', :as => 'block_follower'
  get 'dashboard/(:id)/following' => 'follow#following', :as => 'user_following'
   
  
  match  'dashboard' => 'dashboard#index', :as => :dashboard 
  match 'dashboard/profile' => 'dashboard#my_profile',:as => :dashboard_profile
  match  'dashboard/update/address' => 'dashboard#update_address', :as => :user_address_update 
  match  'dashboard/update/payment_receiving_info' => 'dashboard#payment_receiving_info', :as => :payment_receiving_info 
  match 'dashboard/update/profile'=> 'dashboard#update_profile', :as => :update_profile
  match 'dashboard/images'   => 'dashboard#images',:as => :userimages
  match 'dashboard/videos'   => 'dashboard#videos',:as => :uservideos
  
  match 'dashboard/claim_username/:claim' => 'dashboard#claim_request' ,:as => :claim_request
  
  match 'home/pages/:page_id' => 'home#show_page', :as => :pages_contents
  
  resources :user_images
  resources :user_posts
 resources :settings do
   
   collection do  
    get 'changepassword'
    post 'updatepassword'
    get 'social_accounts' => "authentications#index"
   end
 end
 
 match 'get_nonprofit_from_api' => "nonprofit_search#get_nonprofit_from_api",:as => :get_nonprofit_from_api
 match 'details_donations_made' => "donation_details#details_donations_made", :as => :details_donations_made
 match 'details_donations_received' => "donation_details#details_donations_received", :as => :details_donations_received
 match 'find_non_profits' => "home#find_non_profits", :as => :find_nonprofits
  
  scope "dashboard" do
    resources :campaigns,:controller =>"user_campaigns", :as => "user_campaigns" do 
     member do
        post 'addimage'
        delete 'removeimage/:campaign_image_id' => "user_campaigns#removeimage" ,:as => :removeimage
        
        post 'addvideo'
        delete 'removevideo/:campaign_video_id' => "user_campaigns#removevideo" ,:as => :removevideo
        
        get "donations_campaigns"
        
      end
    end
  end
  
  
  resources :campaign_categories

  resources :members do 
    member do  
      match 'index/:letter' => 'members#members_index' ,:as => :members_index
      scope ':state_id' do 
        match '' => 'members#members_state' ,:as => :members_state
        match 'index/:letter' => 'members#members_state_index' ,:as => :members_state_index
      end
    end
    collection do 
      get 'filter_by_state_and_type'
      post 'filter_by_state_and_type'
    end
  end
  
  
  
 
resources :search do 
   collection do
       
      match 'causes' => "search#causes",:as => :cause
      match 'causes/:key' => "search#cause_results" ,:as => :cause_result
      
      match 'members' => 'search#members' ,:as => :members
      match 'members/:letter' => 'search#members_index' ,:as => :members_index
   end
  end
  
  
  
  resources :campaigns do
    
    collection do 
    get "filter"
    post "filter"
    match '/category/:id' => "campaigns#campaigns_by_category",:as => :by_category
    match '/filter/:sort_order'=> "campaigns#sort_order" ,:as => :filter_sort
    match ':sort_order/state/:state_id'=> "campaigns#state_sort" ,:as => :filter_state_sort
    match ':sort_order/:category_id' => "campaigns#category_sort" ,:as => :filter_category_sort
    match ':sort_order/:category_id/:state_id' => "campaigns#category_state_sort" ,:as => :filter_category_state_sort
      
    end
    get :autocomplete_campaign_title, :on => :collection
    
    collection do
      get "listed_featured_campaign"
    end
    
   end
  
  
  
  
  match '/auth/:provider/callback' => 'authentications#create'
  match '/auth/failure' => 'authentications#failure'
  
  resources :authentications
  
  
  match 'dashboard/update/avatar' => 'dashboard#update_logo', :as => :update_logo
  match 'dashboard/update/sociallinks' => 'dashboard#update_social_links', :as => :social_link_update
  match 'dashboard/update/profile_url' => 'dashboard#update_profile_name',:as => :profile_name_update
 
  match 'donors/(:filter)' => 'home#donors' ,:as => :donors
  match 'sponsors/(:filter)' => 'home#sponsors' ,:as => :sponsors
  match 'users/(:filter)' => 'home#users' ,:as => :users
  
  match 'members'    => 'home#search',:as => :member_search
   
  match 'donation_detail/:donation_id' => "profile#share_donation", :as => :donation_detail
  
  resources :donations 
  match 'makedonation/campaign/:campaign_id' => "donations#new" ,               :as => :campaign_donation
  match 'makedonation/user/:user_id'         => "donations#new" ,               :as => :user_donation 
  match 'makedonation/apiuser/:ein'          =>"donation#unregistered_donation",:as => :apiuser_donation
  
  match 'donation/apinonprofit/:uuid/:ein' => "donations#donation_apinonprofit" ,:as => :api_nonprofitdonation
  match 'makedonation/apinonprofit/:uuid/:ein' => "donations#create_donation_apinonprofit" ,:as => :api_createnonprofitdonation
  

  namespace :admin do
    match  'dashboard' => 'dashboard#index', :as => :dashboard 
    match  'individual_donation' => 'users#donations', :as => :individual_donation
    match  'campaign_donation' => 'campaigns#campaign_donations', :as => :campaign_donation
    match 'apinonprofit_donations' => 'users#api_nonprofitdonations' ,:as => :api_nonprofitdonation
    resources :campaigns do 
      member do
        get "add_to_featured"
        get "removed_from_featured"
       
      end
      
      collection do
    get "featured_campaigns"
       end
      
      
    end
    resources :states
    resources :cities
    resources :featured_users
     resources :pages
    resources :news_letters do 
      member do 
        get "send_news_letter"
      end
     
    end
   resources :reserved_usernames do
   get "approve_request"
   get "reject_request"
 
   end
   
   
   
   
    resources :users do 
    
       get 'campaigns'
      collection do 
      get 'search'
      post 'search'
      get 'filter_by_state_and_type'
      post 'filter_by_state_and_type'
    get 'bytype/:user_type_id'  => 'users#user_filter_by_type', :as => 'user_filter_by_type'
    get 'filter(/:state_id)(/:user_type_id)' => 'users#user_filter', :as => 'user_filter'
    end
       
    end
     
    
  end

  root :to => "home#index"
  

  scope '/:id' do
    match "/" =>"profile#index" , :as => :profile  
    
    match "campaigns" => "profile#campaigns" ,:as => :profile_campaigns
    match "videos" => "profile#videos" ,:as => :profile_videos
    match "images" => "profile#images" ,:as => :profile_images
    match 'follower' => 'profile#follower',:as => :profile_follower
    match 'following' => 'profile#following',:as => :profile_following
    
    match'campaigns/:campaign_id' => "profile#campaign_detail" ,:as => :user_campaign_detail
  end

end

app/models/state.rb
class State < ActiveRecord::Base
  extend FriendlyId
  has_many :cities ,:dependent => :destroy
  has_many :addresses
  accepts_nested_attributes_for :cities, :allow_destroy => :true
  scope :alphabetically ,:order=> "name asc"
   
  friendly_id :name ,use: :slugged
end

app/controllers/admin/states_controller.rb
class Admin::StatesController < ApplicationController
  layout "admin"
  before_filter :require_admin
  # GET /states
  # GET /states.json
  def index
    @states = State.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @states }
    end
  end

  # GET /states/1
  # GET /states/1.json
  def show
    @state = State.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @state }
    end
  end

  # GET /states/new
  # GET /states/new.json
  def new
    @state = State.new
    @city = @state.cities.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @state }
    end
  end

  # GET /states/1/edit
  def edit
    @state = State.find(params[:id])
  end

  # POST /states
  # POST /states.json
  def create
    @state = State.new(params[:state])

    respond_to do |format|
      if @state.save
        format.html { redirect_to admin_state_url(@state), notice: 'State was successfully created.' }
        format.json { render json: @state, status: :created, location: @state }
      else
        format.html { render action: "new" }
        format.json { render json: @state.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /states/1
  # PUT /states/1.json
  def update
    @state = State.find(params[:id])

    respond_to do |format|
      if @state.update_attributes(params[:state])
        format.html { redirect_to admin_state_url(@state), notice: 'State was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @state.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /states/1
  # DELETE /states/1.json
  def destroy
    @state = State.find(params[:id])
    @state.destroy

    respond_to do |format|
      format.html { redirect_to admin_states_url }
      format.json { head :no_content }
    end
  end
end

app/views/admin/states/_city_fields.html.erb
<div class="field control-group">
    <%= f.label :name ,:class=>"control-label" %>
    <div class="controls">
    <%= f.text_field :name %>
    
	<%= link_to_remove_fields "<i class='icon-remove'></i>".html_safe, f %>
	</div>
</div>

app/views/admin/states/_form.html.erb
<%= form_for([:admin,@state]) do |f| %>
  <%= render :partial =>"shared/validation_msg" ,:locals =>{:obj=>@state} %>
  <div class="control-group">
  	<div class="control-label">
    <%= f.label :name %>
    </div>
    <div class="controls">
    <%= f.text_field :name %>
    </div>
  </div>
  <div>
  	Add Cities To state
  <hr />
  <%= f.fields_for :cities do |city| %>
		<%= render :partial => 'city_fields', :locals => {:f => city} %>
    <% end %>
	<%= link_to_add_fields "+ Add City", f, :cities  %>
  </div>	
  <div class="form-actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/states/edit.html.erb
<%= link_to 'State List', admin_states_path,:class=>"btn pull-right" %>

<h5>Editing state</h5>
<hr />
<%= render 'form' %>

app/views/admin/states/index.html.erb
<%= link_to 'New State', new_admin_state_path ,:class=>"btn pull-right" %>

<h3>Listing states</h3>
<br />
<table class="table table-striped table-condensed">
  <tr>
    <th>S.N.</th>
    <th>State</th>
    <th>Actions</th>
  </tr>
<%cnt=0%>
<% @states.each do |state| %>
<%cnt=cnt+1%>
  <tr>
  	<td><%= cnt %></td>
    <td><%= state.name %></td>
    <td>
    	
    	<%= link_to 'Cities', admin_state_path(state) ,:class=>"icon_view"%>
    	<%= link_to '<i class="icon-edit"></i>'.html_safe, edit_admin_state_path(state),:class=>"icon_edit" %>
    	<%= link_to '<i class="icon-trash"></i>'.html_safe, admin_state_path(state), confirm: 'Are you sure?', method: :delete,:class=>"icon-delete" %></td>
  </tr>
<% end %>
</table>

app/views/admin/states/new.html.erb
<%= link_to 'State List', admin_states_path,:class=>"btn pull-right" %>
<h5>New state</h5>
<hr />
<div class="form-horizontal">
<%= render 'form' %>
</div>

app/views/admin/states/show.html.erb
<%= link_to 'State List', admin_states_path %>

<p>
  <b>Name:</b>
  <%= @state.name %>
  
</p>
Cities In this state : 

<% unless @state.cities.nil? %>
	<table>
		<tr class="yellow">
			<th>City</th>
			<th>Action</th>
		</tr>
		<% @state.cities.each do |city| %>
			<tr>
				<td><%= city.name  %></td>
				<td><%= link_to 'Show', admin_city_path(city),:class=>"view button" %> 
    	<%= link_to 'Edit', edit_admin_city_path(city),:class=>"edit button" %>
    	<%= link_to 'Destroy', admin_city_path(city), confirm: 'Are you sure?', method: :delete ,:class => "delete button" %></td>
			</tr>
		<% end %>
	</table>
<% end %>


<%= link_to 'Edit', edit_admin_state_path(@state) %> 